#
# This Docker-compose file is for traefik in a Docker standalone environment
#
# How to:
#
# Create a acme.json file on the host:
# $ touch acme.json && chmod 600 acme.json
#
# Create a user defined bridge network:
# $ docker network create web
#
# The run following command to deploy:
#
# $ docker-compose up
#
# Remember to set email in traefik.toml

version: '3.3'

networks:
  web:
    external: true

services:

  traefik:
    image: traefik
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./acme.json:/acme.json
      - ./traefik.toml:/traefik.toml
    networks:
      - web
    labels:
      - "traefik.enable=false"
