#
# This Docker-compose is for deploying GC2 in a production environment.
# It requires the use of Traefik as reverse proxy.
# Docker-compose file for Traefik is included in this repository.
#
# How to:
#
# Create a file called gc2.env with these vars
#
# GC2_PASSWORD=12345
# TIMEZONE=CET
# LOCALE=en_US.UTF-8
#
# Set the traefik.frontend.rule is this file to your DNS name.
#
# The run following command to deploy:
#
# $ docker-compose up
#
# There will be created named volumes for persistence.
#
# 'docker-compose down' will not remove data
# 'docker-compose down -v' will remove the volumes!!!

version: '3'

networks:
  web:
    external: true
  internal:
    external: false

services:

  gc2core:
    image: mapcentia/gc2core
    privileged: true
    volumes:
      - gc2core_var_www_geocloud2_app_conf:/var/www/geocloud2/app/conf
      - gc2core_var_www_geocloud2_app_wms:/var/www/geocloud2/app/wms
      - gc2core_var_www_geocloud2_app_tmp:/var/www/geocloud2/app/tmp
      - gc2core_var_www_geocloud2_public_logs:/var/www/geocloud2/public/logs
      - gc2core_var_log:/var/log
      - gc2core_var_lib_php_sessions:/var/lib/php/sessions
    env_file:
      - gc2.env
    labels:
      - traefik.backend=gc2core
      - traefik.frontend.rule=Host:gc2.test # SET HOST
      - traefik.port=80
      - traefik.backend.loadbalancer.swarm=false
      - traefik.docker.network=web
      - traefik.frontend.passHostHeader=true
    networks:
      - web
      - internal

  mapcache:
    image: mapcentia/mapcache
    volumes:
      - gc2core_var_www_geocloud2:/var/www/geocloud2
      - mapcache_etc_apache2_sites-enabled:/etc/apache2/sites-enabled
    networks:
      - internal

  postgis:
    image: mapcentia/postgis
    volumes:
      - postgis_var_www_geocloud2:/var/www/geocloud2
      - postgis_var_lib_postgresql:/var/lib/postgresql
      - postgis_var_log:/var/log
      - postgis_etc_postgresql:/etc/postgresql
      - postgis_etc_pgbouncer:/etc/pgbouncer
    env_file:
      - gc2.env
    networks:
      - internal
    ports:
      - "5432:5432"

volumes:
    # gc2core
    gc2core_var_www_geocloud2_app_conf:
    gc2core_var_www_geocloud2_app_wms:
    gc2core_var_www_geocloud2_app_tmp:
    gc2core_var_www_geocloud2_public_logs:
    gc2core_var_log:
    gc2core_var_lib_php_sessions:

    # mapcache
    mapcache_etc_apache2_sites-enabled:

    # postgis
    postgis_var_log:
    postgis_var_www_geocloud2:
    postgis_etc_postgresql:
    postgis_var_lib_postgresql:
    postgis_etc_pgbouncer:



