#
# This Docker-compose is for deploying GC2 and Vidi in a test environment.
# It will expose GC2 on port 8080 and Vidi on 3000
# PostgreSQL password is set to 12345
#
# The run following command to deploy:
#
# $ docker-compose up
#
# There will be created named volumes for persistence.
#
# 'docker-compose down' will not remove data
# 'docker-compose down -v' will remove the volumes!!!
#

version: '3'

networks:
  web:
    external: true

services:
  postgis:
    image: mapcentia/postgis
    volumes:
      - postgis_var_www_geocloud2:/var/www/geocloud2
      - postgis_var_lib_postgresql:/var/lib/postgresql
      - postgis_var_log:/var/log
      - postgis_etc_postgresql:/etc/postgresql
      - postgis_etc_pgbouncer:/etc/pgbouncer
    env_file:
      - postgis.env
    networks:
      - web
    ports:
      - "5432:5432"

volumes:
    postgis_var_log:
    postgis_var_www_geocloud2:
    postgis_etc_postgresql:
    postgis_var_lib_postgresql:
    postgis_etc_pgbouncer:




