#
# The run following commands:
#
# docker-compose up
#
# There will be created named volumes for persistence.
#
# 'docker-compose down' will not remove data
# 'docker-compose down -v' will remove the volumes!!!

version: '3'

networks:
  web:
    external: true

services:
  vidi:
    image: mapcentia/vidi
    volumes:
      - vidi_root_vidi_public_tmp:/root/vidi/public/tmp
      - vidi_tmp_sessions:/tmp/sessions
    deploy:
     labels:
      - traefik.backend=swarm.vidi.io
      - traefik.frontend.rule=Host:vidi.gc2.io # SET HOST
      - traefik.port=3000
      - traefik.backend.loadbalancer.swarm=true
      - traefik.docker.network=web
      - traefik.frontend.passHostHeader=true
    networks:
      - web
volumes:
    vidi_root_vidi_public_tmp:
      driver: cloudstor:aws
      driver_opts:
        backing: shared

    vidi_tmp_sessions:
      driver: cloudstor:aws
      driver_opts:
        backing: shared
