#
# This Docker-compose is for deploying Vidi in a production environment.
# It requires the use of Traefik as reverse proxy.
# Docker-compose file for Traefik is included in this repository.
#
# How to:
#
# Create a file called vidi.env with these vars
#
# GC2_HOST=https://my_gc2_server.com
# TIMEZONE=CET
# LOCALE=en_US.UTF-8
#
# Set the traefik.frontend.rule is this file to your DNS name.
#
# The run following command to deploy:
#
# $ docker-compose up
#
# There will be created named volumes for persistence.
#
# 'docker-compose down' will not remove data
# 'docker-compose down -v' will remove the volumes!!!

version: '3'

networks:
  web:
    external: true

services:

  vidi:
    image: mapcentia/vidi
    ports:
      - "3000:3000"
    volumes:
      - vidi_root_vidi:/root/vidi
    env_file:
      - vidi.env
    networks:
      - web
    labels:
      - traefik.backend=vidi
      - traefik.frontend.rule=Host:vidi.test # SET HOST
      - traefik.port=3000
      - traefik.backend.loadbalancer.swarm=false
      - traefik.docker.network=web
      - traefik.frontend.passHostHeader=true

volumes:
    vidi_root_vidi:




